import type Database from "better-sqlite3";
import { createDoc, header, sectionTitle, paragraph, keyValue, riskBadge, table, footer } from "./pdf.js";
import { getIncidents, type DateRange } from "./stats.js";

interface CheckDetail {
  check: string;
  riskScore: number;
  details: string;
  articleRef?: string;
}

/**
 * Generate an EU AI Act Art. 73 Incident Report.
 * Documents blocked/critical requests with full compliance details.
 *
 * Art. 73 timelines:
 *   - Standard: 15 days after becoming aware
 *   - Widespread/very serious: 2 days
 *   - Death: 10 days
 */
export function generateIncidentReport(db: Database.Database, range: DateRange): PDFKit.PDFDocument {
  const incidents = getIncidents(db, range);
  const doc = createDoc();

  header(
    doc,
    "AI Incident Report",
    `EU AI Act Art. 73 — Serious Incident Documentation | Period: ${range.from} to ${range.to}`,
  );

  paragraph(doc,
    "This report documents AI compliance incidents detected by automated monitoring, " +
    "in accordance with Art. 73 of the EU AI Act (Regulation 2024/1689). Deployers must " +
    "report serious incidents to the market surveillance authority of the Member State " +
    "where the incident occurred.",
  );

  sectionTitle(doc, "Reporting Timelines (Art. 73)");
  paragraph(doc, "  • Standard incidents: within 15 days of becoming aware");
  paragraph(doc, "  • Widespread breach or very serious incident: within 2 days");
  paragraph(doc, "  • Death of a person: within 10 days (initial), 15 days (full)");

  sectionTitle(doc, "Incident Summary");

  keyValue(doc, "Report Period", `${range.from} — ${range.to}`);
  keyValue(doc, "Total Incidents Detected", incidents.length);

  const blocked = incidents.filter((i) => i.actionTaken === "block").length;
  const critical = incidents.filter((i) => i.riskScore >= 9).length;
  const high = incidents.filter((i) => i.riskScore >= 7 && i.riskScore < 9).length;

  keyValue(doc, "Blocked Requests", blocked);
  keyValue(doc, "Critical Severity (Score 9-10)", critical);
  keyValue(doc, "High Severity (Score 7-8)", high);

  if (incidents.length === 0) {
    doc.moveDown(1);
    paragraph(doc, "No incidents detected in this period. Continuous monitoring is active.");
    footer(doc, `Generated by Aulite | ${new Date().toISOString()}`);
    doc.end();
    return doc;
  }

  sectionTitle(doc, "Incident Details");

  for (let idx = 0; idx < Math.min(incidents.length, 50); idx++) {
    const incident = incidents[idx];

    if (doc.y > 680) doc.addPage();

    doc
      .moveDown(0.3)
      .fontSize(11)
      .fillColor("#1a1a2e")
      .text(`Incident #${idx + 1}`, { underline: true })
      .moveDown(0.2);

    keyValue(doc, "Entry ID", incident.id);
    keyValue(doc, "Timestamp", incident.timestamp);
    riskBadge(doc, incident.riskScore, `Risk Level: ${incident.riskLevel.toUpperCase()}`);
    keyValue(doc, "Action Taken", incident.actionTaken.toUpperCase());
    keyValue(doc, "Provider", incident.provider);
    keyValue(doc, "Model", incident.model ?? "—");

    try {
      const domains = JSON.parse(incident.domains);
      if (Array.isArray(domains) && domains.length > 0) {
        keyValue(doc, "Active Domains", domains.join(", "));
      }
    } catch { /* ignore */ }

    try {
      const checks: CheckDetail[] = JSON.parse(incident.checksJson);
      if (checks.length > 0) {
        doc.moveDown(0.3);
        const checkRows = checks.map((c) => [
          c.check,
          String(c.riskScore),
          c.articleRef ?? "—",
          c.details.slice(0, 80),
        ]);
        table(
          doc,
          ["Check", "Score", "Article", "Details"],
          checkRows.slice(0, 10),
          [70, 45, 150, 230],
        );
      }
    } catch { /* ignore */ }

    if (idx < incidents.length - 1) {
      const y = doc.y;
      doc.moveTo(50, y).lineTo(545, y).strokeColor("#eeeeee").lineWidth(0.5).stroke();
    }
  }

  if (incidents.length > 50) {
    doc.moveDown(0.5);
    paragraph(doc, `... and ${incidents.length - 50} more incidents. See full audit trail for complete data.`);
  }

  sectionTitle(doc, "Required Actions (Art. 73(4))");
  paragraph(doc, "[ACTION REQUIRED] For each serious incident, the deployer must:");
  paragraph(doc, "  1. Immediately take corrective action to contain the incident");
  paragraph(doc, "  2. Notify the market surveillance authority within the required timeline");
  paragraph(doc, "  3. Cooperate with the authority's investigation");
  paragraph(doc, "  4. Document investigation findings and corrective measures taken");
  paragraph(doc, "  5. Report includes: AI system identification, incident description,");
  paragraph(doc, "     corrective actions, risk assessment, and any affected persons");

  footer(doc, `Generated by Aulite — EU AI Act Compliance Proxy | ${new Date().toISOString()}`);

  doc.end();
  return doc;
}
