#!/usr/bin/env node
import "dotenv/config";

const command = process.argv[2];

switch (command) {
  case "init":
    await runInit();
    break;
  case "start":
    await runStart();
    break;
  case "domains":
    await runDomains();
    break;
  case "--help":
  case "-h":
  case "help":
    printUsage();
    break;
  default:
    if (command) {
      console.error(`  Unknown command: ${command}\n`);
    }
    printUsage();
    process.exit(command ? 1 : 0);
}

function printUsage(): void {
  console.log(`
  aulite — EU AI Act Compliance Proxy

  Usage:
    aulite init       Set up a new project (interactive wizard)
    aulite start      Start the compliance proxy server
    aulite domains    List available compliance domains
    aulite help       Show this help message

  Environment variables:
    AULITE_DOMAINS    Comma-separated domains (e.g. "hr,finance")
    AULITE_PORT       Server port (default: 3000)
    AULITE_RULES_DIR  Custom rules directory path

  Examples:
    $ aulite init
    $ aulite start
    $ AULITE_DOMAINS=hr,finance aulite start
`);
}

async function runDomains(): Promise<void> {
  const { discoverDomains, loadRulePacks, clearRuleCache } = await import("./rules/loader.js");
  clearRuleCache();
  const domains = discoverDomains();

  const { rules: baseRules } = loadRulePacks([]);
  clearRuleCache();

  console.log(`
  Available compliance domains:
  ${"─".repeat(70)}
  ${"base".padEnd(22)} Always loaded — Art. 5 prohibitions, GDPR Art. 9 (${baseRules.length} rules)
  ${"─".repeat(70)}`);

  for (const d of domains) {
    console.log(`  ${d.name.padEnd(22)} ${d.description} (${d.ruleCount} rules)`);
  }

  console.log(`
  Configure in aulite.config.yml:

    analysis:
      domains:
        - hr
        - finance

  Or via environment variable:

    AULITE_DOMAINS=hr,finance aulite start
`);
}

async function runInit(): Promise<void> {
  const { createInterface } = await import("node:readline/promises");
  const { existsSync, writeFileSync } = await import("node:fs");
  const { discoverDomains, clearRuleCache } = await import("./rules/loader.js");

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  clearRuleCache();

  console.log("\n  Aulite — EU AI Act Compliance Proxy\n");

  const domains = discoverDomains();

  console.log("  Available compliance domains:\n");
  domains.forEach((d, i) => {
    console.log(`    ${String(i + 1).padStart(2)}. ${d.name.padEnd(20)} ${d.description} (${d.ruleCount} rules)`);
  });

  const selection = await rl.question("\n  Select domains (comma-separated numbers, e.g. 1,2): ");
  const indices = selection
    .split(",")
    .map((s) => parseInt(s.trim()) - 1)
    .filter((i) => i >= 0 && i < domains.length);
  const selectedDomains = indices.map((i) => domains[i].name);

  if (selectedDomains.length === 0) {
    console.log("  No valid selection, defaulting to: hr");
    selectedDomains.push("hr");
  }

  const providerInput = await rl.question("\n  AI provider (anthropic/openai) [anthropic]: ");
  const provider = providerInput === "openai" ? "openai" : "anthropic";

  const modeInput = await rl.question("  Analysis mode (advisory/enforcing) [advisory]: ");
  const mode = modeInput === "enforcing" ? "enforcing" : "advisory";

  rl.close();

  const domainsYaml = selectedDomains.map((d) => `    - ${d}`).join("\n");
  const config = `# Aulite Configuration
# EU AI Act Compliance Proxy
# Generated by: aulite init

server:
  port: 3000
  host: "0.0.0.0"

provider:
  default: ${provider}

analysis:
  mode: ${mode}
  domains:
${domainsYaml}
  llmJudge:
    enabled: false
    model: claude-sonnet-4-6
    sampleRate: 0.1
  thresholds:
    warn: 4
    block: 7

logging:
  database: "./aulite-audit.db"
  retentionDays: 365
`;

  const configPath = existsSync("aulite.config.yml") ? "aulite.config.new.yml" : "aulite.config.yml";
  writeFileSync(configPath, config);

  if (configPath !== "aulite.config.yml") {
    console.log(`\n  aulite.config.yml already exists, wrote to: ${configPath}`);
  } else {
    console.log(`\n  Created: ${configPath}`);
  }

  if (!existsSync(".env")) {
    const envKey = provider === "openai" ? "OPENAI_API_KEY=sk-..." : "ANTHROPIC_API_KEY=sk-ant-...";
    writeFileSync(".env", `${envKey}\n`);
    console.log("  Created: .env");
  }

  console.log(`
  Next steps:
    1. Add your ${provider.toUpperCase()} API key to .env
    2. Run: aulite start
    3. Point your AI client to http://localhost:3000
`);
}

async function runStart(): Promise<void> {
  await import("./index.js");
}
